name = "oid4vc-verifier-frontend-hono"
compatibility_date = "2024-10-07"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "PRESENTATION_ID_KV"
id = "c3d306b7436241e590580867d966b4ee"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [dev]
# ip = "0.0.0.0"

[[services]]
binding = "BACKEND"
service = "oid4vc-verifier-endpoint-hono"